<?php

namespace DoctrineORMModule\Proxy\__CG__\Restaurant\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DishInTheRestaurant extends \Restaurant\Entity\DishInTheRestaurant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Restaurant\\Entity\\DishInTheRestaurant' . "\0" . 'id', '' . "\0" . 'Restaurant\\Entity\\DishInTheRestaurant' . "\0" . 'dishName', '' . "\0" . 'Restaurant\\Entity\\DishInTheRestaurant' . "\0" . 'linkToDish', '' . "\0" . 'Restaurant\\Entity\\DishInTheRestaurant' . "\0" . 'priceDish', '' . "\0" . 'Restaurant\\Entity\\DishInTheRestaurant' . "\0" . 'thePopularityOfTheDish', '' . "\0" . 'Restaurant\\Entity\\DishInTheRestaurant' . "\0" . 'recipe', '' . "\0" . 'Restaurant\\Entity\\DishInTheRestaurant' . "\0" . 'photoForDish', '' . "\0" . 'Restaurant\\Entity\\DishInTheRestaurant' . "\0" . 'typeDish'];
        }

        return ['__isInitialized__', '' . "\0" . 'Restaurant\\Entity\\DishInTheRestaurant' . "\0" . 'id', '' . "\0" . 'Restaurant\\Entity\\DishInTheRestaurant' . "\0" . 'dishName', '' . "\0" . 'Restaurant\\Entity\\DishInTheRestaurant' . "\0" . 'linkToDish', '' . "\0" . 'Restaurant\\Entity\\DishInTheRestaurant' . "\0" . 'priceDish', '' . "\0" . 'Restaurant\\Entity\\DishInTheRestaurant' . "\0" . 'thePopularityOfTheDish', '' . "\0" . 'Restaurant\\Entity\\DishInTheRestaurant' . "\0" . 'recipe', '' . "\0" . 'Restaurant\\Entity\\DishInTheRestaurant' . "\0" . 'photoForDish', '' . "\0" . 'Restaurant\\Entity\\DishInTheRestaurant' . "\0" . 'typeDish'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DishInTheRestaurant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setDishName($dishName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDishName', [$dishName]);

        return parent::setDishName($dishName);
    }

    /**
     * {@inheritDoc}
     */
    public function setLinkToDish($linkToDish)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkToDish', [$linkToDish]);

        return parent::setLinkToDish($linkToDish);
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceDish($priceDish)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceDish', [$priceDish]);

        return parent::setPriceDish($priceDish);
    }

    /**
     * {@inheritDoc}
     */
    public function setThePopularityOfTheDish($thePopularityOfTheDish)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThePopularityOfTheDish', [$thePopularityOfTheDish]);

        return parent::setThePopularityOfTheDish($thePopularityOfTheDish);
    }

    /**
     * {@inheritDoc}
     */
    public function setRecipe($recipe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecipe', [$recipe]);

        return parent::setRecipe($recipe);
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotoForDish($photoForDish)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoForDish', [$photoForDish]);

        return parent::setPhotoForDish($photoForDish);
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeDish($typeDish)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeDish', [$typeDish]);

        return parent::setTypeDish($typeDish);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDishName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDishName', []);

        return parent::getDishName();
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkToDish()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkToDish', []);

        return parent::getLinkToDish();
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceDish()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceDish', []);

        return parent::getPriceDish();
    }

    /**
     * {@inheritDoc}
     */
    public function getThePopularityOfTheDish()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThePopularityOfTheDish', []);

        return parent::getThePopularityOfTheDish();
    }

    /**
     * {@inheritDoc}
     */
    public function getRecipe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecipe', []);

        return parent::getRecipe();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoForDish()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoForDish', []);

        return parent::getPhotoForDish();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeDish()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeDish', []);

        return parent::getTypeDish();
    }

}
