<?php

namespace DoctrineORMModule\Proxy\__CG__\Restaurant\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EventsInTheRestaurant extends \Restaurant\Entity\EventsInTheRestaurant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Restaurant\\Entity\\EventsInTheRestaurant' . "\0" . 'id', '' . "\0" . 'Restaurant\\Entity\\EventsInTheRestaurant' . "\0" . 'eventName', '' . "\0" . 'Restaurant\\Entity\\EventsInTheRestaurant' . "\0" . 'briefDescriptionEvent', '' . "\0" . 'Restaurant\\Entity\\EventsInTheRestaurant' . "\0" . 'linkToEvent', '' . "\0" . 'Restaurant\\Entity\\EventsInTheRestaurant' . "\0" . 'thePopularityOfTheEvent', '' . "\0" . 'Restaurant\\Entity\\EventsInTheRestaurant' . "\0" . 'photoForEvents', '' . "\0" . 'Restaurant\\Entity\\EventsInTheRestaurant' . "\0" . 'typeEvent', '' . "\0" . 'Restaurant\\Entity\\EventsInTheRestaurant' . "\0" . 'dateEvent'];
        }

        return ['__isInitialized__', '' . "\0" . 'Restaurant\\Entity\\EventsInTheRestaurant' . "\0" . 'id', '' . "\0" . 'Restaurant\\Entity\\EventsInTheRestaurant' . "\0" . 'eventName', '' . "\0" . 'Restaurant\\Entity\\EventsInTheRestaurant' . "\0" . 'briefDescriptionEvent', '' . "\0" . 'Restaurant\\Entity\\EventsInTheRestaurant' . "\0" . 'linkToEvent', '' . "\0" . 'Restaurant\\Entity\\EventsInTheRestaurant' . "\0" . 'thePopularityOfTheEvent', '' . "\0" . 'Restaurant\\Entity\\EventsInTheRestaurant' . "\0" . 'photoForEvents', '' . "\0" . 'Restaurant\\Entity\\EventsInTheRestaurant' . "\0" . 'typeEvent', '' . "\0" . 'Restaurant\\Entity\\EventsInTheRestaurant' . "\0" . 'dateEvent'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EventsInTheRestaurant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setEventName($eventName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventName', [$eventName]);

        return parent::setEventName($eventName);
    }

    /**
     * {@inheritDoc}
     */
    public function setBrefDescriptionEvent($briefDescriptionEvent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrefDescriptionEvent', [$briefDescriptionEvent]);

        return parent::setBrefDescriptionEvent($briefDescriptionEvent);
    }

    /**
     * {@inheritDoc}
     */
    public function setLinkToEvent($linkToEvent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkToEvent', [$linkToEvent]);

        return parent::setLinkToEvent($linkToEvent);
    }

    /**
     * {@inheritDoc}
     */
    public function setThePopularityOfTheEvent($thePopularityOfTheEvent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThePopularityOfTheEvent', [$thePopularityOfTheEvent]);

        return parent::setThePopularityOfTheEvent($thePopularityOfTheEvent);
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotoForEvents($photoForEvents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoForEvents', [$photoForEvents]);

        return parent::setPhotoForEvents($photoForEvents);
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeEvent($typeEvent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeEvent', [$typeEvent]);

        return parent::setTypeEvent($typeEvent);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEvent($dateEvent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEvent', [$dateEvent]);

        return parent::setDateEvent($dateEvent);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEventName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventName', []);

        return parent::getEventName();
    }

    /**
     * {@inheritDoc}
     */
    public function getBrefDescriptionEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrefDescriptionEvent', []);

        return parent::getBrefDescriptionEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkToEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkToEvent', []);

        return parent::getLinkToEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function getThePopularityOfTheEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThePopularityOfTheEvent', []);

        return parent::getThePopularityOfTheEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoForEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoForEvents', []);

        return parent::getPhotoForEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeEvent', []);

        return parent::getTypeEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEvent', []);

        return parent::getDateEvent();
    }

}
