<?php

namespace DoctrineORMModule\Proxy\__CG__\Restaurant\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SortedKindsOfEventsRestaurant extends \Restaurant\Entity\SortedKindsOfEventsRestaurant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Restaurant\\Entity\\SortedKindsOfEventsRestaurant' . "\0" . 'id', '' . "\0" . 'Restaurant\\Entity\\SortedKindsOfEventsRestaurant' . "\0" . 'linkSortedTypeEvent', '' . "\0" . 'Restaurant\\Entity\\SortedKindsOfEventsRestaurant' . "\0" . 'numberOfPosts', '' . "\0" . 'Restaurant\\Entity\\SortedKindsOfEventsRestaurant' . "\0" . 'photo', '' . "\0" . 'Restaurant\\Entity\\SortedKindsOfEventsRestaurant' . "\0" . 'typeEvent'];
        }

        return ['__isInitialized__', '' . "\0" . 'Restaurant\\Entity\\SortedKindsOfEventsRestaurant' . "\0" . 'id', '' . "\0" . 'Restaurant\\Entity\\SortedKindsOfEventsRestaurant' . "\0" . 'linkSortedTypeEvent', '' . "\0" . 'Restaurant\\Entity\\SortedKindsOfEventsRestaurant' . "\0" . 'numberOfPosts', '' . "\0" . 'Restaurant\\Entity\\SortedKindsOfEventsRestaurant' . "\0" . 'photo', '' . "\0" . 'Restaurant\\Entity\\SortedKindsOfEventsRestaurant' . "\0" . 'typeEvent'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SortedKindsOfEventsRestaurant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setLinkSortedTypeEvent($linkSortedTypeEvent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkSortedTypeEvent', [$linkSortedTypeEvent]);

        return parent::setLinkSortedTypeEvent($linkSortedTypeEvent);
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberOfPosts($numberOfPosts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberOfPosts', [$numberOfPosts]);

        return parent::setNumberOfPosts($numberOfPosts);
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeEvent($typeEvent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeEvent', [$typeEvent]);

        return parent::setTypeEvent($typeEvent);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkSortedTypeEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkSortedTypeEvent', []);

        return parent::getLinkSortedTypeEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberOfPosts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberOfPosts', []);

        return parent::getNumberOfPosts();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeEvent', []);

        return parent::getTypeEvent();
    }

}
