

<body>

    <section class="hero-wrap hero-wrap-2" style="background-image: url(<?= $this->basePath($data_action['photoHeadId']['photo']) ?>);">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">Контакты</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="<?= $this->url('restaurant',['action'=>'index']) ?>">Главная <i class="ion-ios-arrow-forward"></i></a></span> <span>Контакты<i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section ftco-no-pb contact-section">
      <div class="container">
        <div class="row block-9">
            <div class="col-md-6 order-md-last d-flex message_contact_form">
              <!--  
              <form action="#" class="bg-light p-5 contact-form">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Your Name">
                </div>
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Your Email">
                </div>
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Subject">
                </div>
                <div class="form-group">
                  <textarea name="" id="" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
                </div>
                <div class="form-group">
                  <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
                </div>
              </form>

               --> 
               <?= $this->form()->openTag($contact_form
                            ->setAttributes(['class'=>'bd-light p-5 contact-form'])) ?> 

              <div class="form-group">
                  <?= $this->formLabel($contact_form->get('name_human')) ?>
                  <?= $this->formElement($contact_form->get('name_human')
                          ->setAttributes(['class'=>'form-control',
                              'placeholder' => 'Укажите Имя Фамилию Отчество'])) ?>
                  <?= $this->formElementErrors($contact_form->get('name_human')) ?>
              </div>
                <div class="error_message_contact" >
                    <div class="toast2" role="alert" aria-live="assertive" aria-atomic="false">
                        <div class="ml-2 mb-1 close_message_contact" data-dismiss="toast" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </div>

                        <div class="toast2-body">
                            Сообщение
                        </div>
                    </div>
                </div>
              <div class="form-group"> 
                  <?= $this->formLabel($contact_form->get('human_email')) ?>
                  <?= $this->formElement($contact_form->get('human_email')
                          ->setAttributes(['class'=>'form-control',
                              'placeholder' => 'Укажите E-mail для ответа'])) ?>
                  <?= $this->formElementErrors($contact_form->get('human_email')) ?>
              </div>
               <div class="error_message_contact" >
                    <div class="toast2" role="alert" aria-live="assertive" aria-atomic="false">
                        <div class="ml-2 mb-1 close_message_contact" data-dismiss="toast" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </div>

                        <div class="toast2-body">
                            Сообщение
                        </div>
                    </div>
                </div>
              <div class="form-group">
                  <?= $this->formLabel($contact_form->get('human_topic')) ?>
                  <?= $this->formElement($contact_form->get('human_topic')
                          ->setAttributes(['class'=>'form-control',
                              'placeholder' => 'Укажите тему сообщение'])) ?>
                  <?= $this->formElementErrors($contact_form->get('human_topic')) ?>
              </div>
               <div class="error_message_contact" >
                    <div class="toast2" role="alert" aria-live="assertive" aria-atomic="false">
                        <div class="ml-2 mb-1 close_message_contact" data-dismiss="toast" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </div>

                        <div class="toast2-body">
                            Сообщение
                        </div>
                    </div>
                </div>
              <div class="form-group">
                  <?= $this->formLabel($contact_form->get('human_message')) ?>
                  <?= $this->formElement($contact_form->get('human_message')
                          ->setAttributes(['class'=>'form-control',
                              'placeholder' => 'Сообщение',
                              'cols'=>30,'rows'=>7])) ?>
                  <?= $this->formElementErrors($contact_form->get('human_message')) ?>
              </div>
               <div class="error_message_contact" >
                    <div class="toast2" role="alert" aria-live="assertive" aria-atomic="false">
                        <div class="ml-2 mb-1 close_message_contact" data-dismiss="toast" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </div>

                        <div class="toast2-body">
                            Сообщение
                        </div>
                    </div>
                </div>
              <div class="form-group">
                  <?= $this->formElement($contact_form->get('submit')
                        ->setAttributes(['class'=>'btn btn-primary py-3 px-5 submitContact'])) ?>
              </div>
               
                <div class="error_message_contact message_contact_all" >
                    <div class="toast2" role="alert" aria-live="assertive" aria-atomic="false">
                        <div class="ml-2 mb-1 close_message_contact" data-dismiss="toast" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </div>

                        <div class="toast2-body">
                            Сообщение
                        </div>
                    </div>
                </div>
               
               
              <?= $this->formElement($contact_form->get('csrf')); ?>
              <?= $this->form()->closeTag(); ?>
                
            </div>

            <div class="col-md-6 d-flex">
                <!--<div id="map" class="bg-white"></div>-->
                <?= $data_action['contentWithAdress'] ?>
            </div>
        </div>
        
      </div>
    </section>
		
    <section class="ftco-section contact-section">
      <div class="container">
        <div class="row d-flex contact-info">
          <div class="col-md-3 d-flex">
          	<div class="align-self-stretch box p-4 text-center">
          		<div class="icon d-flex align-items-center justify-content-center">
          			<span class="icon-map-signs"></span>
          		</div>
          		<h3 class="mb-4">Адрес</h3>
	            <p><?= $data_action['adressCompanyText'] ?></p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="align-self-stretch box p-4 text-center">
          		<div class="icon d-flex align-items-center justify-content-center">
          			<span class="icon-phone2"></span>
          		</div>
          		<h3 class="mb-4">Телефон</h3>
	            <p> <?= $data_action['telephoneCompany'] ?> <!--<a href="tel://1234567920">+ 1235 2355 98</a>--></p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="align-self-stretch box p-4 text-center">
          		<div class="icon d-flex align-items-center justify-content-center">
          			<span class="icon-paper-plane"></span>
          		</div>
          		<h3 class="mb-4">Email</h3>
	            <p><a href="mailto:<?= $data_action['emailCompany'] ?>"><?= $data_action['emailCompany'] ?></a></p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="align-self-stretch box p-4 text-center">
          		<div class="icon d-flex align-items-center justify-content-center">
          			<span class="icon-globe"></span>
          		</div>
          		<h3 class="mb-4">Website</h3>
	            <p><?= $data_action['linkAdressSite'] ?></p>
	          </div>
          </div>
        </div>
      </div>
    </section>

  </body>
