
  
  <body>

    <section class="hero-wrap hero-wrap-2" style="background-image: url(<?= $this->basePath($data_action[1]['photo']['photo']) ?>);">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">Еда</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="<?= $this->url('restaurant',['action'=>'index']) ?>">Главная <i class="ion-ios-arrow-forward"></i></a></span> <span>Еда <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>


    <section class="ftco-section">
    	<div class="container">
        <div class="row">
        	<div class="col-lg-9">
        		<div class="row">
                            <?php foreach($data_action[3] as $foods): ?>
                                <div class="col-md-4 ftco-animate">
                                    <div class="blog-entry">
                                        <a href="<?= $foods['linkToDish'] ?>" class="img-2"><img src="<?= $this->basePath($foods['photoForDish']['photo']) ?>" class="img-fluid1" alt="Colorlib Template"></a>
                                        <div class="text pt-3">
                                            <p class="meta d-flex"><span class="pr-3"><?= $foods['typeDish']['typeDish']['namecategory'] ?></span><span class="ml-auto pl-3"><?= $foods['priceDish'] ?></span></p>
                                            <h3><a href="<?= $foods['linkToDish'] ?>"><?= $foods['dishName'] ?></a></h3>
                                            <p class="mb-0"><a href="<?= $foods['linkToDish'] ?>" class="btn btn-black py-2">Читать больше <span class="icon-arrow_forward ml-4"></span></a></p>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                            <!--
        			<div class="col-md-4 ftco-animate">
    						<div class="blog-entry">
		    					<a href="<?php // $this->url('restaurant', ['action'=>'single']) ?>" class="img-2"><img src="<?php //$this->basePath('images/blog-1.jpg') ?>" class="img-fluid" alt="Colorlib Template"></a>
			    				<div class="text pt-3">
	    							<p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span></p>
	    							<h3><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>">Tasty &amp; Delicious Foods</a></h3>
	    							<p class="mb-0"><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="btn btn-black py-2">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
	    						</div>
		    				</div>
    					</div>
                            
    					<div class="col-md-4 ftco-animate">
    						<div class="blog-entry">
		    					<a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="img-2"><img src=" <?php //$this->basePath('images/blog-2.jpg') ?>" class="img-fluid" alt="Colorlib Template"></a>
			    				<div class="text pt-3">
	    							<p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span></p>
	    							<h3><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>">Tasty &amp; Delicious Foods</a></h3>
	    							<p class="mb-0"><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="btn btn-black py-2">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
	    						</div>
		    				</div>
    					</div>
    					<div class="col-md-4 ftco-animate">
    						<div class="blog-entry">
		    					<a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="img-2"><img src=" <?php //$this->basePath('images/blog-3.jpg') ?>" class="img-fluid" alt="Colorlib Template"></a>
			    				<div class="text pt-3">
	    							<p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span></p>
	    							<h3><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>">Tasty &amp; Delicious Foods</a></h3>
	    							<p class="mb-0"><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="btn btn-black py-2">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
	    						</div>
		    				</div>
    					</div>
    					<div class="col-md-4 ftco-animate">
    						<div class="blog-entry">
		    					<a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="img-2"><img src="<?php //$this->basePath('images/blog-4.jpg')  ?>" class="img-fluid" alt="Colorlib Template"></a>
			    				<div class="text pt-3">
	    							<p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span></p>
	    							<h3><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>">Tasty &amp; Delicious Foods</a></h3>
	    							<p class="mb-0"><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="btn btn-black py-2">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
	    						</div>
		    				</div>
    					</div>
    					<div class="col-md-4 ftco-animate">
    						<div class="blog-entry">
		    					<a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="img-2"><img src="<?php //$this->basePath('images/blog-5.jpg') ?>" class="img-fluid" alt="Colorlib Template"></a>
			    				<div class="text pt-3">
	    							<p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span></p>
	    							<h3><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>">Tasty &amp; Delicious Foods</a></h3>
	    							<p class="mb-0"><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="btn btn-black py-2">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
	    						</div>
		    				</div>
    					</div>
    					<div class="col-md-4 ftco-animate">
    						<div class="blog-entry">
		    					<a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="img-2"><img src="<?php //$this->basePath('images/blog-6.jpg') ?>" class="img-fluid" alt="Colorlib Template"></a>
			    				<div class="text pt-3">
	    							<p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span></p>
	    							<h3><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>">Tasty &amp; Delicious Foods</a></h3>
	    							<p class="mb-0"><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="btn btn-black py-2">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
	    						</div>
		    				</div>
    					</div>
    					<div class="col-md-4 ftco-animate">
    						<div class="blog-entry">
		    					<a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="img-2"><img src="<?php //$this->basePath('images/blog-7.jpg') ?>" class="img-fluid" alt="Colorlib Template"></a>
			    				<div class="text pt-3">
	    							<p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span></p>
	    							<h3><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>">Tasty &amp; Delicious Foods</a></h3>
	    							<p class="mb-0"><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="btn btn-black py-2">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
	    						</div>
		    				</div>
    					</div>
    					<div class="col-md-4 ftco-animate">
    						<div class="blog-entry">
		    					<a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="img-2"><img src="<?php //$this->basePath('images/blog-8.jpg') ?>" class="img-fluid" alt="Colorlib Template"></a>
			    				<div class="text pt-3">
	    							<p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span></p>
	    							<h3><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>">Tasty &amp; Delicious Foods</a></h3>
	    							<p class="mb-0"><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="btn btn-black py-2">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
	    						</div>
		    				</div>
    					</div>
    					<div class="col-md-4 ftco-animate">
    						<div class="blog-entry">
		    					<a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="img-2"><img src="<?php //$this->basePath('images/blog-9.jpg') ?>" class="img-fluid" alt="Colorlib Template"></a>
			    				<div class="text pt-3">
	    							<p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span></p>
	    							<h3><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>">Tasty &amp; Delicious Foods</a></h3>
	    							<p class="mb-0"><a href="<?php //$this->url('restaurant', ['action'=>'single']) ?>" class="btn btn-black py-2">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
	    						</div>
		    				</div>
    					</div>
                            -->
        		</div>
        		<?php if( $data_action[4]['page'] > 1 ): ?>
                            <div class="row mt-5">
                              <div class="col text-center">
                                <div class="block-27">
                                    <ul>
                                        <?php if( $data_action[4]['page'] == 2 ): ?>  
                                            
                                            <?php if( $data_action[4]['current_page'] == 1 ): ?>
                                                <li><a>&lt;</a></li>
                                                <li class="active"><span>1</span></li>
                                                <li><a href="<?= $data_action[4]['link'][1] ?>">2</a></li>
                                                <li><a href="<?= $data_action[4]['link'][1] ?>">&gt;</a></li>
                                            <?php else : ?>
                                                <li><a href="<?= $data_action[4]['link'][0] ?>">&lt;</a></li>
                                                <li><a href="<?= $data_action[4]['link'][0] ?>">1</a></li>
                                                <li class="active"><span>2</span></li>
                                                <li><a>&gt;</a></li>
                                            <?php endif; ?>    
                                            
                                        <?php endif; ?>
                                    
                                        <?php if($data_action[4]['page'] == 3): ?>
                                                <?php if( $data_action[4]['current_page'] == 1 ): ?>
                                                    <li><a>&lt;</a></li>
                                                    <li class="active"><span>1</span></li>
                                                    <li><a href="<?= $data_action[4]['page'][1] ?>">2</a></li>
                                                    <li><a href="<?= $data_action[4]['page'][2] ?>">3</a></li>
                                                    <li><a href="<?= $data_action[4]['next'] ?>">&gt;</a></li>
                                                <?php endif; ?>
                                                <?php if( $data_action[4]['current_page'] == 2 ): ?>
                                                    <li><a href="<?= $data_action[4]['prev'] ?>">&lt;</a></li>
                                                    <li><a href="<?= $data_action[4]['link'][0] ?>">1</a></li>
                                                    <li class="active"><span>2</span></li>
                                                    <li><a href="<?= $data_action[4]['link'][2] ?>">3</a></li>
                                                    <li><a href="<?= $data_action[4]['next'] ?>">&gt;</a></li>
                                                <?php endif; ?>
                                                <?php if( $data_action[4]['current_page'] == 3 ): ?>
                                                    <li><a href="<?= $data_action[4]['prev'] ?>">&lt;</a></li>
                                                    <li><a href="<?= $data_action[4]['link'][0] ?>">1</a></li>
                                                    <li><a href="<?= $data_action[4]['link'][1] ?>">2</a></li>
                                                    <li class="active"><span>3</span></li>
                                                    <li><a>&gt;</a></li>
                                                <?php endif; ?>
                                        <?php endif; ?>
                                            
                                        <?php if($data_action[4]['page'] == 4): ?>
                                                    <?php if( $data_action[4]['current_page'] == 1 ): ?>
                                                        <li><a>&lt;</a></li>
                                                        <li class="active"><span>1</span></li>
                                                        <li><a href="<?= $data_action[4]['link'][1] ?>">2</a></li>
                                                        <li><a href="<?= $data_action[4]['link'][2] ?>">3</a></li>
                                                        <li><a href="<?= $data_action[4]['link'][3] ?>">4</a></li>
                                                        <li><a href="<?= $data_action[4]['next'] ?>">&gt;</a></li>
                                                    <?php endif;?> 
                                                    <?php if( $data_action[4]['current_page'] == 2 ): ?>
                                                        <li><a href="<?= $data_action[4]['prev'] ?>">&lt;</a></li>
                                                        <li><a href="<?= $data_action[4]['link'][0] ?>">1</a></li>
                                                        <li class="active"><span>2</span></li>
                                                        <li><a href="<?= $data_action[4]['link'][2] ?>">3</a></li>
                                                        <li><a href="<?= $data_action[4]['link'][3] ?>">4</a></li>
                                                        <li><a href="<?= $data_action[4]['next'] ?>">&gt;</a></li>
                                                    <?php endif;?>
                                                    <?php if( $data_action[4]['current_page'] == 3 ): ?>
                                                        <li><a href="<?= $data_action[4]['prev'] ?>">&lt;</a></li>
                                                        <li><a href="<?= $data_action[4]['link'][0] ?>">1</a></li>
                                                        <li><a href="<?= $data_action[4]['link'][1] ?>">2</a></li>
                                                        <li class="active"><span>3</span></li>
                                                        <li><a href="<?= $data_action[4]['link'][3] ?>">4</a></li>
                                                        <li><a href="<?= $data_action[4]['next'] ?>">&gt;</a></li>
                                                    <?php endif;?>
                                                    <?php if( $data_action[4]['current_page'] == 4 ): ?>
                                                        <li><a href="<?= $data_action[4]['prev'] ?>">&lt;</a></li>
                                                        <li><a href="<?= $data_action[4]['link'][0] ?>">1</a></li>
                                                        <li><a href="<?= $data_action[4]['link'][1] ?>">2</a></li>
                                                        <li><a href="<?= $data_action[4]['link'][2] ?>">3</a></li>
                                                        <li class="active"><span>4</span></li>
                                                        <li><a>&gt;</a></li>
                                                    <?php endif;?>
                                        <?php endif; ?>
                                        <?php if( $data_action[4]['page'] > 4 ): ?>  
                                            <?php if($data_action[4]['link']['prev'] != null): ?>
                                                <li><a href="<?= $data_action[4]['link']['prev'] ?>">&lt;</a></li>
                                                <li><a href="<?= $data_action[4]['link']['start']?>">1</a></li>
                                            <?php else: ?>
                                                <li><a>&lt;</a></li>
                                                <li class="active"><span>1</span></li>
                                            <?php endif; ?>
                                            
                                            <!-- если первая страница -->
                                            <?php if( $data_action[4]['current_page'] == 1 ): ?>
                                                <li><a href="<?= $data_action[4]['link']['next'] ?>">2</a></li>
                                                <li><a href="<?= $data_action[4]['link']['ellipsis'] ?>">&#8226; &#8226; &#8226;</a></li>
                                            <?php endif; ?>
                                            <!-- если вторая страница -->
                                            <?php if( $data_action[4]['current_page'] == 2 ): ?>
                                                <li class="active"><span>2</span></li>
                                                <li><a href="<?= $data_action[4]['link']['next'] ?>"><?= $data_action[4]['next_page'] ?></a></li>
                                                <li><a href="<?= $data_action[4]['link']['ellipsis'] ?>">&#8226; &#8226; &#8226;</a></li>
                                            <?php endif; ?>
                                            <!-- если третья страница -->
                                            <?php if( $data_action[4]['current_page'] == 3 ): ?>
                                                <li><a href="<?= $data_action[4]['link']['prev'] ?>"><?= $data_action[4]['prev_page'] ?></a></li>
                                                <li class="active"><span>3</span></li>
                                                <li><a href="<?= $data_action[4]['link']['next'] ?>"><?= $data_action[4]['next_page'] ?></a></li>
                                                <?php if( $data_action[4]['link']['ellipsis'] != null ): ?>
                                                    <li><a href="<?= $data_action[4]['link']['ellipsis'] ?>">&#8226; &#8226; &#8226;</a></li>
                                                <?php endif;?>
                                            <?php endif; ?>
                                            <!-- последняя страница -->
                                            <?php if($data_action[4]['current_page'] == $data_action[4]['page'] ): ?>
                                                <li><a href="<?= $data_action[4]['link']['ellipsis'] ?>">&#8226; &#8226; &#8226;</a></li>
                                                <li><a href="<?= $data_action[4]['link']['prev'] ?>"><?= $data_action[4]['prev_page'] ?></a></li>
                                            <?php endif; ?> 
                                            <!-- предпоследняя страница -->
                                            <?php if($data_action[4]['current_page'] == ($data_action[4]['page'] - 1) ): ?>
                                                <li><a href="<?= $data_action[4]['link']['ellipsis'] ?>">&#8226; &#8226; &#8226;</a></li>
                                                <li><a href="<?= $data_action[4]['link']['prev'] ?>"><?= $data_action[4]['prev_page'] ?></a></li>
                                                <li class="active"><span><?= $data_action[4]['page'] - 1 ?></span></li>
                                            <?php endif; ?>
                                            <!-- предпредпоследняя страница --> 
                                            <?php if( $data_action[4]['current_page'] == ($data_action[4]['page'] - 2) &&
                                                    $data_action[4]['current_page'] != 3 ): ?>
                                                <?php if($data_action[4]['link']['ellipsis'] != null): ?>
                                                    <li><a href="<?= $data_action[4]['link']['ellipsis'] ?>">&#8226; &#8226; &#8226;</a></li>
                                                <?php endif; ?>
                                                <li><a href="<?= $data_action[4]['link']['prev'] ?>"><?= $data_action[4]['prev_page'] ?></a></li>
                                                <li class="active"><span><?= $data_action[4]['current_page'] ?></span></li>
                                                <li><a href="<?= $data_action[4]['link']['next'] ?>"><?= $data_action[4]['next_page'] ?></a></li>
                                            <?php endif; ?>
                                            <!-- если где-то в середине -->
                                            <?php if( $data_action[4]['current_page'] > 3 && $data_action[4]['current_page'] < ($data_action[4]['page'] - 2) ): ?>
                                                <li><a href="<?= $data_action[4]['link']['prev'] ?>"><?= $data_action[4]['prev_page'] ?></a></li>
                                                <li class="active"><span><?= $data_action[4]['current_page'] ?></span></li>
                                                <li><a href="<?= $data_action[4]['link']['next'] ?>"><?= $data_action[4]['next_page'] ?></a></li>
                                                <li><a href="<?= $data_action[4]['link']['ellipsis'] ?>">&#8226; &#8226; &#8226;</a></li>
                                                
                                            <?php endif; ?>
                                            
                                            <?php if($data_action[4]['link']['next'] != null): ?>
                                                <li><a href="<?= $data_action[4]['link']['end'] ?>"><?= $data_action[4]['page'] ?></a></li>
                                                <li><a href="<?= $data_action[4]['link']['next'] ?>">&gt;</a></li>
                                            <?php else: ?>
                                                <li class="active"><span><?= $data_action[4]['page'] ?></span></li>
                                                <li><a>&gt;</a></li>
                                            <?php endif ; ?>
                                                
                                        <?php endif; ?>
                                        
                                    </ul>
                                </div>
                              </div>
                            </div>
                        <?php endif; ?>
        	</div>

        	<div class="col-lg-3">
        		<div class="sidebar-wrap">
                            <div class="sidebar-box p-4 about text-center ftco-animate">
			        <h2 class="heading mb-4"><?= $data_action[2]['head'] ?></h2>
			        <img src="<?= $this->basePath($data_action[2]['photo']['photo']) ?>" class="img-fluid1" alt="Colorlib Template">
			        <div class="text pt-4">
                                    <p><?= $data_action[2]['textMenu'] ?></p>
			        </div>
                            </div>
                            <!--
	        		<div class="sidebar-box p-4 ftco-animate">
                                    <form action="#" class="search-form">
                                      <div class="form-group">
                                        <span class="icon icon-search"></span>
                                        <input type="text" class="form-control" placeholder="Search">
                                      </div>
                                    </form>
                                </div>
                            -->
	            <div class="sidebar-box categories text-center ftco-animate">
			<h2 class="heading mb-4">Категории</h2>
                            <ul class="category-image">
                                <?php foreach($data_action[0] as $category ): ?>
                                    <li>
                                        <a href="<?= $category['typeDish']['link'] ?>" class="img d-flex align-items-center justify-content-center text-center" style="background-image: url(<?= $this->basePath($category['photo']) ?>);">
                                                <div class="text">
                                                        <h3><?= $category['typeDish']['namecategory'] ?></h3>
                                                </div>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                                    
                                    <li>
                                        <a href="<?= $this->url('restaurant',['action'=>'foods']) ?>" class="img d-flex align-items-center justify-content-center text-center" style="background-image: url(<?= $this->basePath('images/image_6.jpg')?>)"  >
                                            <div class="text">
                                                <h3>Все категории</h3>
                                            </div>
                                        </a>
                                        
                                    </li>
                                    
                                <!--
                                <li>
                                        <a href="#" class="img d-flex align-items-center justify-content-center text-center" style="background-image: url(<?php // $this->basePath('images/category-1.jpg')?>);">
                                                <div class="text">
                                                        <h3>Foods</h3>
                                                </div>
                                        </a>
                                </li>
                                <li>
                                        <a href="#" class="img d-flex align-items-center justify-content-center text-center" style="background-image: url(<?php // $this->basePath('images/category-2.jpg') ?>);">
                                                <div class="text">
                                                        <h3>Lifestyle</h3>
                                                </div>
                                        </a>
                                </li>
                                <li>
                                        <a href="#" class="img d-flex align-items-center justify-content-center text-center" style="background-image: url(<?php // $this->basePath('images/category-2.jpg') ?>);">
                                                <div class="text">
                                                        <h3>Others</h3>
                                                </div>
                                        </a>
                                </li>
                                -->
                            </ul>
                    </div>
            </div>
        	</div>
        </div>
    	</div>
    </section>


  </body>
