
  <body>
    
    <section class="home-slider owl-carousel">
        <?php foreach($data_action[0]['scroll'] as $product_best):  ?>

            <div class="slider-item">
                <div class="container">
                    <div class="row d-flex slider-text justify-content-center align-items-center" data-scrollax-parent="true">

                        <div class="img" style="background-image: url(<?= $this->basePath($product_best['t_about_us']['photoForDish']['photo']) ?>);"></div>

                        <div class="text d-flex align-items-center ftco-animate">
                            <div class="text-2 pb-lg-5 mb-lg-4 px-4 px-md-5">
                                <h3 class="subheading mb-3">Популярные блюда</h3>
                                <h1 class="mb-5"><?= $product_best['food_']['dishName'] ?></h1>
                                <p class="mb-md-5">Одно из самых популярных блюд в ресторане</p>
                                <p><a href="<?= $product_best['food_']['linkToDish'] ?>" class="btn btn-black px-3 px-md-4 py-3">Читать больше <span class="icon-arrow_forward ml-lg-4"></span></a></p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        <?php endforeach; ?>
        
        <!--
        <div class="slider-item">
            <div class="container">
                <div class="row d-flex slider-text justify-content-center align-items-center" data-scrollax-parent="true">
						
                    <div class="img" style="background-image: url(<?php // $this->basePath('images/bg_1.jpg') ?>);"></div>

                    <div class="text d-flex align-items-center ftco-animate">
                        <div class="text-2 pb-lg-5 mb-lg-4 px-4 px-md-5">
                            <h3 class="subheading mb-3">Featured Posts</h3>
                            <h1 class="mb-5">Love the Delicious &amp; Tasty Foods</h1>
                            <p class="mb-md-5">A small river named Duden flows by their place and supplies it with the necessary regelialia</p>
                            <p><a href="#" class="btn btn-black px-3 px-md-4 py-3">Read More <span class="icon-arrow_forward ml-lg-4"></span></a></p>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="slider-item">
            <div class="container">
                <div class="row d-flex slider-text justify-content-center align-items-center" data-scrollax-parent="true">

                    <div class="img" style="background-image: url(<?php // $this->basePath('images/bg_2.jpg') ?>);"></div>

                    <div class="text d-flex align-items-center ftco-animate">
                        <div class="text-2 pb-lg-5 mb-lg-4 px-4 px-md-5">
                                <h3 class="subheading mb-3">Featured Posts</h3>
                                <h1 class="mb-5">I am A Blogger &amp; I Love Foods</h1>
                                <p class="mb-md-5">A small river named Duden flows by their place and supplies it with the necessary regelialia</p>
                                <p><a href="#" class="btn btn-black px-3 px-md-4 py-3">Read More <span class="icon-arrow_forward ml-lg-4"></span></a></p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        
        -->
    </section>

    <section class="ftco-section">
    	<div class="container">
            <div class="row">
                <div class="col-md-7 heading-section ftco-animate">
                    <h2 class="mb-4"><span>Разные блюда</span></h2>
                </div>
            </div>
            <div class="row">
                <?php $i = 0; foreach($data_action[0]['different'] as $different_food): ?>
                <?php if($i == 0 ): ?>
                <?php $i=1; ?>
                <!--
                <div class="col-md-6 order-md-last col-lg-6 ftco-animate">
                    <div class="blog-entry">
                        <div class="img img-big d-flex align-items-end" style="background-image: url(<?= $this->basePath('images/image_2.jpg') ?>);">
                            <div class="overlay"></div>
                            <div class="text">
                                <span class="subheading">Блюдо</span>
                                <h3><a href="single.html">Tasty &amp; Delicious Foods</a></h3>
                                <p class="mb-0"><a href="single.html" class="btn-custom">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
                            </div>
                        </div>
                    </div>
                </div>
                -->
                <div class="col-md-6 order-md-last col-lg-6 ftco-animate">
                    <div class="blog-entry">
                        <div class="img img-big d-flex align-items-end" style="background-image: url(<?= $this->basePath($different_food['t_about_us']['photoForDish']['photo']) ?>);">
                            <div class="overlay"></div>
                            <div class="text">
                                <span class="subheading"><?= $different_food['t_about_us']['typeDish']['typeDish']['namecategory'] ?></span>
                                <h3><a href="<?= $different_food['food_']['linkToDish'] ?>"><?= $different_food['food_']['dishName'] ?></a></h3>
                                <p class="mb-0"><a href="<?= $different_food['food_']['linkToDish'] ?>" class="btn-custom">Читать больше <span class="icon-arrow_forward ml-4"></span></a></p>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-6">
                    
                    <div class="row">
                        <?php else: ?>
                            <div class="col-md-6 ftco-animate">
                                <div class="blog-entry">
                                    <a href="<?= $different_food['food_']['linkToDish'] ?>" class="img d-flex align-items-end" style="background-image: url(<?= $this->basePath($different_food['t_about_us']['photoForDish']['photo']) ?>);">
                                        <div class="overlay"></div>
                                    </a>
                                    <div class="text pt-3">
                                        <p class="meta d-flex"><span class="pr-3"><?= $different_food['t_about_us']['typeDish']['typeDish']['namecategory'] ?></span><span class="ml-auto pl-3">Категория</span></p>
                                        <h3><a href="<?= $different_food['food_']['linkToDish'] ?>"><?= $different_food['food_']['dishName'] ?></a></h3>
                                        <p class="mb-0"><a href="<?= $different_food['food_']['linkToDish'] ?>" class="btn-custom">Читать больше <span class="icon-arrow_forward ml-4"></span></a></p>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?> 
                        <?php endforeach; ?>
                        <!--
                        <div class="col-md-6 ftco-animate">
                            <div class="blog-entry">
                                <a href="single.html" class="img d-flex align-items-end" style="background-image: url(<?= $this->basePath('images/image_1.jpg') ?>);">
                                    <div class="overlay"></div>
                                </a>
                                <div class="text pt-3">
                                    <p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span></p>
                                    <h3><a href="single.html">Tasty &amp; Delicious Foods</a></h3>
                                    <p class="mb-0"><a href="single.html" class="btn-custom">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 ftco-animate">
                            <div class="blog-entry">
                                <a href="single.html" class="img d-flex align-items-end" style="background-image: url(<?= $this->basePath('images/image_3.jpg') ?>);">
                                    <div class="overlay"></div>
                                </a>
                                <div class="text pt-3">
                                    <p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span></p>
                                    <h3><a href="single.html">Tasty &amp; Delicious Foods from Scotland</a></h3>
                                    <p class="mb-0"><a href="single.html" class="btn-custom">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 ftco-animate">
                            <div class="blog-entry">
                                <a href="single.html" class="img d-flex align-items-end" style="background-image: url(<?= $this->basePath('images/image_4.jpg') ?>);">
                                    <div class="overlay"></div>
                                </a>
                                <div class="text pt-3">
                                    <p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span></p>
                                    <h3><a href="single.html">Tasty &amp; Delicious Foods</a></h3>
                                    <p class="mb-0"><a href="single.html" class="btn-custom">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 ftco-animate">
                            <div class="blog-entry">
                                <a href="single.html" class="img d-flex align-items-end" style="background-image: url(<?= $this->basePath('images/image_5.jpg') ?>);">
                                    <div class="overlay"></div>
                                </a>
                                <div class="text pt-3">
                                    <p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span></p>
                                    <h3><a href="single.html">Tasty &amp; Delicious Foods</a></h3>
                                    <p class="mb-0"><a href="single.html" class="btn-custom">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>
                        -->
                        
                    </div>
                      
                
                </div>
                
                
            </div>
    	</div>
    </section>
    
    <section class="ftco-section ftco-no-pt">
    	<div class="container">
        <div class="row">
        	<div class="col-lg-9">
        		<div class="row">
                            <div class="col-md-12 heading-section ftco-animate">
                                <h2 class="mb-4"><span>События в ресторане</span></h2>
                            </div>
		        </div>
        		<div class="row">
                            <?php if($data_action[2] != null): ?>
                            <?php foreach($data_action[2] as $event): ?>
                                <div class="col-md-4 ftco-animate">
                                    <div class="blog-entry">
                                        <a href="<?= $event['event_']['linkToEvent'] ?>" class="img-2"><img src="<?= $this->basePath($event['t_about_us']['photoForEvents']['photo']) ?>" class="img-fluid img-event-main" alt="Colorlib Template"></a>
                                        <div class="text pt-3">
                                            <p class="meta d-flex"><span class="pr-3">Дата события</span><span class="ml-auto pl-3"><?= $event['t_about_us']['dateEvent']['date']->format('Y-m-d') ?></span></p>
                                            <h3><a href="<?= $event['event_']['linkToEvent'] ?>"><?= $event['event_']['eventName'] ?></a></h3>
                                            <p class="mb-0"><a href="<?= $event['event_']['linkToEvent'] ?>" class="btn btn-black py-2"> Читать больше <span class="icon-arrow_forward ml-4"></span></a></p>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <!--
        			<div class="col-md-4 ftco-animate">
    						<div class="blog-entry">
		    					<a href="single.html" class="img-2"><img src="<?php // $this->basePath('images/blog-1.jpg') ?>" class="img-fluid" alt="Colorlib Template"></a>
			    				<div class="text pt-3">
	    							<p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span></p>
	    							<h3><a href="#">Tasty &amp; Delicious Foods</a></h3>
	    							<p class="mb-0"><a href="single.html" class="btn btn-black py-2">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
	    						</div>
		    				</div>
    					</div>
    					<div class="col-md-4 ftco-animate">
    						<div class="blog-entry">
		    					<a href="single.html" class="img-2"><img src="<?php // $this->basePath('images/blog-2.jpg') ?>" class="img-fluid" alt="Colorlib Template"></a>
			    				<div class="text pt-3">
	    							<p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span></p>
	    							<h3><a href="#">Tasty &amp; Delicious Foods</a></h3>
	    							<p class="mb-0"><a href="single.html" class="btn btn-black py-2">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
	    						</div>
		    				</div>
    					</div>
    					<div class="col-md-4 ftco-animate">
    						<div class="blog-entry">
		    					<a href="single.html" class="img-2"><img src="<?php // $this->basePath('images/blog-3.jpg') ?>" class="img-fluid" alt="Colorlib Template"></a>
			    				<div class="text pt-3">
	    							<p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span></p>
	    							<h3><a href="#">Tasty &amp; Delicious Foods</a></h3>
	    							<p class="mb-0"><a href="single.html" class="btn btn-black py-2">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
	    						</div>
		    				</div>
    					</div>
                            -->
        		</div>
        	</div>
                <?php if($data_action[4] != null): ?>
        	<div class="col-lg-3">
        		<div class="sidebar-wrap">
	        		<div class="sidebar-box p-4 about text-center ftco-animate">
			          <h2 class="heading mb-4"><?= $data_action[4]['side_menu']['head'] ?></h2>
			          <img src="<?= $this->basePath($data_action[4]['t_about_us']['photo']['photo']) ?>" class="img-fluid" alt="Colorlib Template">
			          <div class="text pt-4">
                                      <p><?= $data_action[4]['side_menu']['textMenu'] ?></p>
			          </div>
	        		</div>
                            <!--
	        		<div class="sidebar-box p-4 ftco-animate">
                                    
                                    <form action="#" class="search-form">
                                      <div class="form-group">
                                        <span class="icon icon-search"></span>
                                        <input type="text" class="form-control" placeholder="Search">
                                      </div>
                                    </form>
                                   
                                </div> 
                            -->
                        </div>
        	</div>
            <?php endif; ?>
        </div>
    	</div>
    </section>

    <section class="ftco-section ftco-no-pt ftco-section-about ftco-no-pb bg-darken">
    	<div class="container-fluid">
            <div class="row">
		<div class="col-sm-6 col-md-6 col-lg-9 order-md-last img py-5" style="background-image: url(<?= $this->basePath($data_action[3]['t_about_us']['photoHuman']['photo']) ?>);"></div>

	        <div class="col-sm-6 col-md-6 col-lg-3 py-4 text d-flex align-items-center ftco-animate">
	        	<div class="text-2 py-5 px-4">
                            <?php if($data_action[3]['t_about_us']['video'] != null ): ?>
                                <p class="mb-5"><a href="https://vimeo.com/45830194" class="btn-custom popup-vimeo">Watch Video <span class="ion-ios-play ml-4"></span></a></p>
                            <?php endif; ?>
	            <h1 class="mb-5"><?= $data_action[3]['nameHuman1'] ?></h1>
	            <p class="mb-md-5"><?= $data_action[3]['t_about_us']['textHistory'] ?></p>
	            <span class="signature"><?= $data_action[3]['t_about_us']['nameHuman'] ?></span>
	          </div>
	        </div>
            </div>
    	</div>
    </section>

    <section class="ftco-section">
    	<div class="container">
        <div class="row">
        	<div class="col-md-9">
        		<div class="row">
		          <div class="col-md-12 heading-section ftco-animate">
		            <h2 class="mb-4"><span>Рецепты популярных блюд</span></h2>
		          </div>
		        </div>
        		<div class="row">
                            <?php foreach($data_action[0]['recipe'] as $food_recipe): ?>
                                <div class="col-md-6 col-lg-6 ftco-animate">
                                    <div class="blog-entry">
                                        <div class="img img-big img-big-2 d-flex align-items-end" style="background-image: url(<?= $this->basePath($food_recipe['t_about_us']['photoForDish']['photo']) ?>);">
                                            <div class="overlay"></div>
                                            <div class="text">
                                                <span class="subheading"><?= $food_recipe['t_about_us']['typeDish']['typeDish']['namecategory'] ?></span>
                                                <h3><a href="<?= $food_recipe['food_']['linkToDish'] ?>"><?= $food_recipe['food_']['dishName'] ?></a></h3>
                                                <p class="mb-0"><a href="<?= $food_recipe['food_']['linkToDish'] ?>" class="btn-custom">Читать Далее<span class="icon-arrow_forward ml-4"></span></a></p>
                                            </div>
                                        </div>
                                    </div>
		    		</div>
                            <?php endforeach; ?>
                            <!--
        			<div class="col-md-6 col-lg-6 ftco-animate">
		    				<div class="blog-entry">
		    					<div class="img img-big img-big-2 d-flex align-items-end" style="background-image: url(<?php // $this->basePath('images/image_1.jpg') ?>);">
		    						<div class="overlay"></div>
		    						<div class="text">
                                                                    <span class="subheading">Food</span>
                                                                    <h3><a href="#">ham sandwich on white surface</a></h3>
                                                                    <p class="mb-0"><a href="#" class="btn-custom">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
		    						</div>
			    				</div>
		    				</div>
		    		</div>
		    			<div class="col-md-6 col-lg-6 ftco-animate">
		    				<div class="blog-entry">
		    					<div class="img img-big img-big-2 d-flex align-items-end" style="background-image: url(<?php // $this->basePath('images/image_3.jpg') ?>);">
		    						<div class="overlay"></div>
		    						<div class="text">
		    							<span class="subheading">Lifestyle</span>
		    							<h3><a href="#">White and red ceramic plate</a></h3>
		    							<p class="mb-0"><a href="#" class="btn-custom">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
		    						</div>
			    				</div>
		    				</div>
		    			</div>
                            -->
        		</div>
        	</div>
        	<div class="col-md-3">
                    <div class="sidebar-wrap pt-4">
                        <div class="sidebar-box categories text-center ftco-animate">
			    <h2 class="heading mb-4">Категории</h2>
                            <ul class="category-image">
                                <?php foreach($data_action[1] as $category_food): ?>
                                    <li>
                                        <a href="<?= $category_food['t_about_us']['typeDish']['link'] ?>" class="img d-flex align-items-center justify-content-center text-center" style="background-image: url(<?= $this->basePath($category_food['t_about_us']['photo']['photo']) ?>);">
                                            <div class="text">
                                                <h3><?= $category_food['t_about_us']['typeDish']['namecategory'] ?></h3>
                                            </div>
                                        </a>
                                    </li>
                                <?php endforeach;?>
                                    <!--
                                    <li>
                                            <a href="foods.html" class="img d-flex align-items-center justify-content-center text-center" style="background-image: url(<?= $this->basePath('images/category-1.jpg') ?>);">
                                                    <div class="text">
                                                            <h3>Foods</h3>
                                                    </div>
                                            </a>
                                    </li>
                                    <li>
                                            <a href="lifestyle.html" class="img d-flex align-items-center justify-content-center text-center" style="background-image: url(<?= $this->basePath('images/category-2.jpg') ?>);">
                                                    <div class="text">
                                                            <h3>Lifestyle</h3>
                                                    </div>
                                            </a>
                                    </li>
                                    <li>
                                            <a href="#" class="img d-flex align-items-center justify-content-center text-center" style="background-image: url(<?= $this->basePath('images/category-2.jpg') ?>);">
                                                    <div class="text">
                                                            <h3>Others</h3>
                                                    </div>
                                            </a>
                                    </li>
                                    -->
                            </ul>
	        	</div>
                    </div>
        	</div>
        </div>
    	</div>
    </section>
   	
    <section class="ftco-counter ftco-section ftco-no-pt ftco-no-pb img" id="section-counter">
    	<div class="container">
    		<div class="row d-flex">
    			<div class="col-md-6 d-flex">
    				<div class="img d-flex align-self-stretch" style="background-image:url(<?= $this->basePath($data_action[3]['t_about_us']['photoAbout']['photo']) ?>);"></div>
    			</div>
    			<div class="col-md-6 pl-md-5 py-5">
    				<div class="row justify-content-start pb-3">
		          <div class="col-md-12 heading-section ftco-animate">
		            <h2 class="mb-4"><?= $data_action[3]['t_about_us']['headHistory'] ?></h2>
		            <p><?= $data_action[3]['t_about_us']['textHistory'] ?></p>
		          </div>
		        </div>
		    		<div class="row">
		          <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
		            <div class="block-18 text-center py-5 bg-light mb-4">
		              <div class="text">
		                <strong class="number" data-number="<?= $data_action[3]['t_about_us']['number1'] ?>">0</strong>
		                <span><?= $data_action[3]['t_about_us']['title1'] ?></span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
		            <div class="block-18 text-center py-5 bg-light mb-4">
		              <div class="text">
		                <strong class="number" data-number="<?= $data_action[3]['t_about_us']['number2'] ?>">0</strong>
		                <span><?= $data_action[3]['t_about_us']['title2'] ?></span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
		            <div class="block-18 text-center py-5 bg-light mb-4">
		              <div class="text">
		                <strong class="number" data-number="<?= $data_action[3]['t_about_us']['number3'] ?>">0</strong>
		                <span><?= $data_action[3]['t_about_us']['title3'] ?></span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
		            <div class="block-18 text-center py-5 bg-light mb-4">
		              <div class="text">
		                <strong class="number" data-number="<?= $data_action[3]['t_about_us']['number4'] ?>">0</strong>
		                <span><?= $data_action[3]['t_about_us']['title4'] ?></span>
		              </div>
		            </div>
		          </div>
		        </div>
	        </div>
        </div>
    	</div>
    </section>

	<!--	
    <section class="ftco-subscribe ftco-section bg-light">
        <div class="overlay">
            <div class="container">
                <div class="row d-flex justify-content-center">
                  <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                    <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
                    <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                    <div class="row d-flex justify-content-center mt-4 mb-4">
                      <div class="col-md-8">
                        <form action="#" class="subscribe-form">
                          <div class="form-group d-flex">
                            <input type="text" class="form-control" placeholder="Enter email address">
                            <input type="submit" value="Subscribe" class="submit px-3">
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </section>
        -->
  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

  </body>
  <!--
</html> -->
