<?php
?>



<body>
    <br><br><br><br><br><br>
    <h1>Редактирование страницы Контакты</h1>
    
    <?php if(isset($edite['fon'])): ?>
        <section class="fon--table">
        
            <table>
                <tr>
                    <th colspan="6">таблица для редактирования фона страницы</th>
                </tr>
                <tr>
                    <th>id</th>
                    <th>Страница</th>
                    <th>Фото в табл. id</th>
                    <th>Фото в табл. путь</th>
                    <th>фото</th> 
                    <th>Действие</th>
                </tr>
                    <?php foreach($edite['fon'] as $editeFon ): ?>
                        <tr>
                            <td><?= $editeFon['id'] ?></td>
<?php switch($editeFon['page']): ?>
<?php case(1): ?>
                            <td data-td="1"> Страница с событиями </td>
<?php break; ?>
<?php case(2): ?>
                            <td data-td="2"> Страница с едой </td>
<?php break; ?>
<?php case(3): ?>
                            <td data-td="3"> Главная страница сайта </td>
<?php break; ?>
<?php case(4): ?>
                            <td data-td="4"> Страница статья событие </td>
<?php break; ?>
<?php case(5): ?>
                            <td data-td="5"> Страница статья еда </td>
<?php break; ?>
<?php endswitch; ?>
                            <td><?= $editeFon['photo']['id'] ?></td>
                            <td><?= $editeFon['photo']['photo'] ?> </td>
                            <td><img class="fon-photo-edite" src="<?= $this->basePath($editeFon['photo']['photo']) ?>"></td>
                            <td>
                                <input type="button" value="Изменить" class="button-table buttoneditefon">
                                <input type="button" value="Удалить" class="button-table buttondeletefon">
                            </td>
                        </tr>
                        
                <?php endforeach; ?>
                <tr class="copy-column-fon-table">
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><img src="<?= $this->basePath() ?>" class="fon-photo-edite"></td>
                    <td>
                        <input type="button" value="Изменить" class="button-table buttoneditefon">
                        <input type="button" value="Удалить" class="button-table buttondeletefon">
                    </td>
                </tr>
            </table>
        
        </section>
    <?php else: ?>
    
        <section class="fon--table">
        
            <table>
                <tr>
                    <th colspan="6">таблица для редактирования фона страницы</th>
                </tr>
                <tr>
                    <th>id</th>
                    <th>Страница</th>
                    <th>Фото в табл. id</th>
                    <th>Фото в табл. путь</th>
                    <th>фото</th> 
                    <th>Действие</th>
                </tr>
                
                <tr class="copy-column-fon-table">
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><img src="<?= $this->basePath() ?>" class="fon-photo-edite" ></td>
                    <td>
                        <input type="button" value="Изменить" class="button-table buttoneditefon">
                        <input type="button" value="Удалить" class="button-table buttondeletefon">
                    </td>
                </tr>
            </table>
        
        </section>
    
    <?php endif; ?>
    <!-- -->
    <?= $this->form($form_fon) ?>
    
    <section class="hero-wrap hero-wrap-2 contact-head-fon " style="background-image: url(<?= $this->basePath($data_action['photoHeadId']['photo']) ?>);">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">Контакты</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="<?= $this->url('restaurant',['action'=>'index']) ?>">Главная <i class="ion-ios-arrow-forward"></i></a></span> <span>Контакты<i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>
    
    <!-- Таблица с фото -->
    <section class="image--table">
        <div class="image-scroll-table">
            <table>
                <?php if( isset($edite['image']) ): ?>
                    <tr>
                        <th colspan = "4">
                            Редактирование таблицы фото
                        </th>
                    </tr>
                    <tr>
                        <th>id</th>
                        <th>Путь</th>
                        <th>фото</th>
                        <th>Действие</th>
                    </tr>
                    <?php $i_count = 0; ?>
                    <?php foreach($edite['image'] as $image): ?>
                        <tr>
                            <td><?= $image['id'] ?></td>
                            <td><?= $image['photo'] ?></td>
                            <td><img class="fon-photo-edite" src="<?= $this->basePath($image['photo']) ?>"></td>
                            <td>
                                <input type="button" value="Изменить" class="button-table buttonediteimage">
                                <input type="button" value="Удалить" class="button-table buttondeleteimage">
                            </td>
                        </tr>
                        <?php $i_count++; ?>
                    <?php endforeach; ?>

                <?php else: ?>
                        <tr>
                            <th colspan = "4">
                                Редактирование таблицы фото
                            </th>
                        </tr>
                        <tr>
                            <th>id</th>
                            <th>Путь</th>
                            <th>фото</th>
                            <th>Действие</th>
                        </tr>
                        <?php $i_count = 0; ?>
                <?php endif; ?>
                <tr class="copy-column-image-table">
                    <td></td>
                    <td></td>
                    <td><img class="fon-photo-edite" src="<?= $this->basePath() ?>"></td>
                    <td>
                        <input type="button" value="Изменить" class="button-table buttonediteimage">
                        <input type="button" value="Удалить" class="button-table buttondeleteimage">
                    </td>
                </tr>
                
            </table>
        </div>
        <?php if(isset($edite['image_param'])):
            ?>
            <div class="photo-param"> показано записей <b><span class="current_count_photo"><?= $i_count ?></span></b> из <b><span class="end_count_photo" ><?= $edite['image_param']['image_end'] ?></span></b></div>
            <div data-url="<?= $this->basePath('siteediting/all-form') ?>" class="photo_pagination_contact" data-current-start-count="<?= $edite['image_param']['image_start'] ?>" data-current-max-count="<?= $edite['image_param']['image_end'] ?>" data-step="<?= $edite['image_param']['image_step'] ?>">
                >>
            </div>
        <?php endif; ?>
        <?= $this->form($form_image); ?>
    </section>
    
    <!-- Таблица с контактами -->
   <?php if( isset($edite['contact']) ): ?>
        <section class="contact--table">
            <table>
                <tr>
                    <th colspan="7"> Таблица для страницы с контактами </th>
                </tr>
                <tr>
                    <th>id</th>
                    <th>id Фото загол.</th>
                    <th>Путь Фото загол.</th>
                    <th>Фото загол.</th>
                    <th>Контент с адресом</th>
                    <th>Контент вид на сайте</th>
                    <th>Адрес компании</th>
                    <th>Телефоны компании</th>
                    <th>Email компании</th>
                    <th>Ссылка на сайт </th>
                    <th>Действие</th>
                </tr>
                <?php foreach($edite['contact'] as $edite): ?>
                    <tr>
                        <td><?= $edite['id'] ?></td>
                        <td><?= $edite['photoHeadId']['id'] ?></td>
                        <td><?= $edite['photoHeadId']['photo'] ?></td>
                        <td><img class="fon-photo-edite" src="<?= $this->basePath($edite['photoHeadId']['photo']) ?>"></td>
                        <td><?= $edite['contentWithAdress_code'] ?></td>
                        <td style="width:100px"><?= $edite['contentWithAdress'] ?></td>
                        <td><?= $edite['adressCompanyText'] ?></td>
                        <td><?= $edite['telephoneCompany'] ?></td>
                        <td><?= $edite['emailCompany'] ?></td>
                        <td><?= $edite['linkAdressSite'] ?></td>
                        <td>
                            <input type="button" value="Изменить" class="button-table buttoneditecontact">
                            <input type="button" value="Удалить" class="button-table buttondeletecontact">
                        </td>
                    </tr>
                <?php endforeach; ?>
                <tr class="copy-column-contact-table">
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><img class="fon-photo-edite" src="<?= $this->basePath() ?>"></td>
                    <td></td>
                    <td style="width: 100px"></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <input type="button" value="Изменить" class="button-table buttoneditecontact">
                        <input type="button" value="Удалить" class="button-table buttondeletecontact">
                    </td>
                </tr>
            </table>
            <?= $this->form($form_contact) ?>
        </section>
    <?php else: ?>
        <section class="contact--table">
            <table>
                <tr>
                    <th colspan="7"> Таблица для страницы с контактами </th>
                </tr>
                <tr>
                    <th>id</th>
                    <th>id Фото загол.</th>
                    <th>Путь Фото загол.</th>
                    <th>Фото загол.</th>
                    <th>Контент с адресом</th>
                    <th>Контент вид на сайте</th>
                    <th>Адрес компании</th>
                    <th>Телефоны компании</th>
                    <th>Email компании</th>
                    <th>Ссылка на сайт </th>
                    <th>Действие</th>
                </tr>
                <tr class="copy-column-contact-table">
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><img class="fon-photo-edite" src="<?= $this->basePath() ?>"></td>
                    <td></td>
                    <td style="width: 100px"></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <input type="button" value="Изменить" class="button-table buttoneditecontact">
                        <input type="button" value="Удалить" class="button-table buttondeletecontact">
                    </td>
                </tr>
            </table>
            <?= $this->form($form_contact) ?>
        </section>
    <?php endif; ?>
    <section class="ftco-section ftco-no-pb contact-section contact-section-edite_1">
      <div class="container">
        <div class="row block-9">
            <div class="col-md-6 order-md-last d-flex message_contact_form">
              
               <?= $this->form()->openTag($contact_form
                            ->setAttributes(['class'=>'bd-light'])) ?> 

              <div class="form-group">
                  <?= $this->formLabel($contact_form->get('name_human')) ?>
                  <?= $this->formElement($contact_form->get('name_human')
                          ->setAttributes(['class'=>'form-control',
                              'placeholder' => 'Укажите Имя Фамилию Отчество'])) ?>
                  <?= $this->formElementErrors($contact_form->get('name_human')) ?>
              </div>
                <div class="error_message_contact" >
                    <div class="toast2" role="alert" aria-live="assertive" aria-atomic="false">
                        <div class="ml-2 mb-1 close_message_contact" data-dismiss="toast" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </div>

                        <div class="toast2-body">
                            Сообщение
                        </div>
                    </div>
                </div>
              <div class="form-group"> 
                  <?= $this->formLabel($contact_form->get('human_email')) ?>
                  <?= $this->formElement($contact_form->get('human_email')
                          ->setAttributes(['class'=>'form-control',
                              'placeholder' => 'Укажите E-mail для ответа'])) ?>
                  <?= $this->formElementErrors($contact_form->get('human_email')) ?>
              </div>
               <div class="error_message_contact" >
                    <div class="toast2" role="alert" aria-live="assertive" aria-atomic="false">
                        <div class="ml-2 mb-1 close_message_contact" data-dismiss="toast" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </div>

                        <div class="toast2-body">
                            Сообщение
                        </div>
                    </div>
                </div>
              <div class="form-group">
                  <?= $this->formLabel($contact_form->get('human_topic')) ?>
                  <?= $this->formElement($contact_form->get('human_topic')
                          ->setAttributes(['class'=>'form-control',
                              'placeholder' => 'Укажите тему сообщение'])) ?>
                  <?= $this->formElementErrors($contact_form->get('human_topic')) ?>
              </div>
               <div class="error_message_contact" >
                    <div class="toast2" role="alert" aria-live="assertive" aria-atomic="false">
                        <div class="ml-2 mb-1 close_message_contact" data-dismiss="toast" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </div>

                        <div class="toast2-body">
                            Сообщение
                        </div>
                    </div>
                </div>
              <div class="form-group">
                  <?= $this->formLabel($contact_form->get('human_message')) ?>
                  <?= $this->formElement($contact_form->get('human_message')
                          ->setAttributes(['class'=>'form-control',
                              'placeholder' => 'Сообщение',
                              'cols'=>30,'rows'=>7])) ?>
                  <?= $this->formElementErrors($contact_form->get('human_message')) ?>
              </div>
               <div class="error_message_contact" >
                    <div class="toast2" role="alert" aria-live="assertive" aria-atomic="false">
                        <div class="ml-2 mb-1 close_message_contact" data-dismiss="toast" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </div>

                        <div class="toast2-body">
                            Сообщение
                        </div>
                    </div>
                </div>
              <div class="form-group">
                  <?= $this->formElement($contact_form->get('submit')
                        ->setAttributes(['class'=>'btn btn-primary'])) ?>
              </div>
               
                <div class="error_message_contact message_contact_all" >
                    <div class="toast2" role="alert" aria-live="assertive" aria-atomic="false">
                        <div class="ml-2 mb-1 close_message_contact" data-dismiss="toast" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </div>

                        <div class="toast2-body">
                            Сообщение
                        </div>
                    </div>
                </div>
               
               
              <?= $this->formElement($contact_form->get('csrf')); ?>
              <?= $this->form()->closeTag(); ?>
                
            </div>

            <div class="col-md-6 d-flex contact-address-content">
                <!--<div id="map" class="bg-white"></div>-->
                <?= $data_action['contentWithAdress'] ?>
            </div>
        </div>
        
      </div>
    </section>
		
    <section class="ftco-section contact-section contact-section-edite_2">
      <div class="container">
        <div class="row d-flex contact-info">
          <div class="col-md-3 d-flex d-flex-1">
          	<div class="align-self-stretch box p-4 text-center">
          		<div class="icon d-flex align-items-center justify-content-center">
          			<span class="icon-map-signs"></span>
          		</div>
          		<h3 class="mb-4">Адрес</h3>
	            <p><?= $data_action['adressCompanyText'] ?></p>
	        </div>
          </div>
          <div class="col-md-3 d-flex  d-flex-1">
          	<div class="align-self-stretch box p-4 text-center">
          		<div class="icon d-flex align-items-center justify-content-center">
          			<span class="icon-phone2"></span>
          		</div>
          		<h3 class="mb-4">Телефон</h3>
	            <p> <?= $data_action['telephoneCompany'] ?> <!--<a href="tel://1234567920">+ 1235 2355 98</a>--></p>
	        </div>
          </div>
          <div class="col-md-3 d-flex  d-flex-1">
          	<div class="align-self-stretch box p-4 text-center">
          		<div class="icon d-flex align-items-center justify-content-center">
          			<span class="icon-paper-plane"></span>
          		</div>
          		<h3 class="mb-4">Email</h3>
	            <p><a href="mailto:<?= $data_action['emailCompany'] ?>"><?= $data_action['emailCompany'] ?></a></p>
	        </div>
          </div>
          <div class="col-md-3 d-flex  d-flex-1">
          	<div class="align-self-stretch box p-4 text-center">
          		<div class="icon d-flex align-items-center justify-content-center">
          			<span class="icon-globe"></span>
          		</div>
          		<h3 class="mb-4">Website</h3>
	            <p><?= $data_action['linkAdressSite'] ?></p>
	        </div>
          </div>
        </div>
      </div>
    </section>
    конец страницы
  </body>
