<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <!--
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        -->
        <!--
        <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,900" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i,900,900i" rel="stylesheet">

        <link rel="stylesheet" href="css/open-iconic-bootstrap.min.css">
        <link rel="stylesheet" href="css/animate.css">

        <link rel="stylesheet" href="css/owl.carousel.min.css">
        <link rel="stylesheet" href="css/owl.theme.default.min.css">
        <link rel="stylesheet" href="css/magnific-popup.css">

        <link rel="stylesheet" href="css/aos.css">

        <link rel="stylesheet" href="css/ionicons.min.css">

        <link rel="stylesheet" href="css/flaticon.css">
        <link rel="stylesheet" href="css/icomoon.css">
        <link rel="stylesheet" href="css/style.css">
        -->
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, shrink-to-fit=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!--
        <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,900" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i,900,900i" rel="stylesheet">
        -->
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            //->prependStylesheet($this->basePath('css/style.css'))
           // ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            /*
            ->prependStylesheet($this->basePath('css/open-iconic-bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/animate.css'))
            ->prependStylesheet($this->basePath('css/owl.carousel.min.css'))
            ->prependStylesheet($this->basePath('css/owl.theme.default.min.css'))
            ->prependStylesheet($this->basePath('css/magnific-popup.css'))
            ->prependStylesheet($this->basePath('css/aos.css'))
            ->prependStylesheet($this->basePath('css/ionicons.min.css'))
            ->prependStylesheet($this->basePath('css/flaticon.css'))
            ->prependStylesheet($this->basePath('css/icomoon.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            */
        ->prependStylesheet($this->basePath('css/style_restaurant.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/icomoon.css'))
        ->prependStylesheet($this->basePath('css/flaticon.css'))
        ->prependStylesheet($this->basePath('css/ionicons.min.css'))
        ->prependStylesheet($this->basePath('css/aos.css'))
        ->prependStylesheet($this->basePath('css/magnific-popup.css'))
        ->prependStylesheet($this->basePath('css/owl.theme.default.min.css'))
        ->prependStylesheet($this->basePath('css/owl.carousel.min.css'))
        ->prependStylesheet($this->basePath('css/animate.css'))
        ->prependStylesheet($this->basePath('css/open-iconic-bootstrap.min.css'))
            
        ?>
        <!--<link rel="stylesheet" href="<?php // $this->basePath('css/style.css') ?>">
        -->
        <!-- Scripts -->
        <?php /* $this->inlineScript()
            //->prependFile($this->basePath('js/bootstrap.min.js'))
            //->prependFile($this->basePath('js/js_restaurant/'))
            ->prependFile($this->basePath('js/js_restaurant/jquery.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/jquery-migrate-3.0.1.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/popper.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/bootstrap.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/jquery.easing.1.3.js'))
            ->prependFile($this->basePath('js/js_restaurant/jquery.waypoints.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/jquery.stellar.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/owl.carousel.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/jquery.magnific-popup.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/aos.js'))
            ->prependFile($this->basePath('js/js_restaurant/jquery.animateNumber.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/scrollax.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/google-map.js'))
            ->prependFile($this->basePath('js/js_restaurant/main.js'))
            //->prependFile($this->basePath('js/js_restaurant/'))
            */
        ?>
        <!--
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
        -->
    </head>
    <body>
        <!--
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?php // $this->url('home') ?>">
                        <img src="<?php //$this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?php // \Application\Module::VERSION ?>"/>&nbsp;Skeleton Application1
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?php // $this->url('home') ?>">Home <span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?php //$this->url('application') ?>">Application <span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?php //$this->url('user',['action'=>'index']) ?>">User <span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?php //$this->url('onemodule') ?>">Onemodule <span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?php //$this->url('onemodule',['action'=>'one']) ?>">New Onemodule <span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?php //$this->url('onemodule',['action'=>'patterndelegirovaniy']) ?>">delegation design pattern<span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?php //$this->url('restaurant') ?>"> Restaurant home <span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?php //$this->url('restaurant',['action'=>'about']) ?>"> Restaurant about <span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?php //$this->url('restaurant',['action'=>'contact']) ?>"> Restaurant contact <span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                </div>
                
            </div>
        </nav>
        -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="index.html">Stories<span>.</span></a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
                  <li class="nav-item"><a href="<?=  $this->url('home') ?>" class="nav-link" >Home Zend</a></li>
	          <li class="nav-item active"><a href="<?= $this->url('restaurant',['action'=>'index']) ?>" class="nav-link">Home</a></li>
	          <li class="nav-item"><a href="<?= $this->url('restaurant',['action'=>'about']) ?>" class="nav-link">About</a></li>
	          <li class="nav-item"><a href="<?= $this->url('restaurant',['action'=>'foods']) ?>" class="nav-link">Foods</a></li>
	          <li class="nav-item"><a href="<?= $this->url('restaurant',['action'=>'lifestyle']) ?>" class="nav-link">Lifestyle</a></li>
	          <li class="nav-item"><a href="<?= $this->url('restaurant',['action'=>'contact']) ?>" class="nav-link">Contact</a></li>
	        </ul>
	      </div>
	    </div>
	</nav>
    <!-- END nav -->
        <div class="container1">
            <?= $this->content ?>
            
            <!--<hr>
            <footer>
                <p>&copy; 2055 - <?php // date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
                это мой шаблон
            </footer>
            -->
            <section class="ftco-subscribe ftco-section bg-light">
                <div class="overlay">
                  <div class="container">
                    <div class="row d-flex justify-content-center">
                      <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                        <h2 class="mb-4"><span><?= $this->var2['heading'] ?> </span></h2>
                        <p><?= $this->var2['textMenu'] ?></p>
                        <div class="row d-flex justify-content-center mt-4 mb-4">
                          <div class="col-md-8">
                            
                            <!-- Форма для подписки E-mail клиента -->
                                <?= $this->form()->openTag($mailform
                                        ->setAttributes(['class'=>'subscribe-form'])) ?>

                                <div class="form-group d-flex">
                                    <?= $this->formLabel($mailform->get('email')) ?>
                                    <?= $this->formElement($mailform->get('email')
                                            ->setAttributes(['class'=>'form-control',
                                                'placeholder'=>'Введите свой E-mail'])) ?>
                                    <?= $this->formElementErrors($mailform->get('email')) ?>

                                    <?= $this->formElement($mailform->get('submit')
                                            ->setAttributes(['class'=>'submit px-3 emailbutton']) ) ?>    
                                </div>
                                <?= $this->formElement($mailform->get('csrf')); ?>
                                <?= $this->form()->closeTag(); ?>
                            
                            <div class="error_message" >
                                <div class="toast1" role="alert" aria-live="assertive" aria-atomic="false">
                                    <div class="ml-2 mb-1 close_message_email" data-dismiss="toast" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </div>
                                    
                                    <div class="toast1-body">
                                        Сообщение
                                    </div>
                                </div>
                            </div>
                          </div>
                            <!-- вывод формы целиком
                            <div class="col-md-8">
                                <?php // $this->form($mailform); ?>
                            </div>
                            <div class="col-md-8">
                                <?php // $this->form()->render($mailform); ?>
                            </div>
                            -->
                            
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
            </section>
            
            
            <footer class="ftco-footer ftco-footer-2 ftco-section">
                <div class="container">
                    <div class="row mb-5">
                      <div class="col-md">
                        <div class="ftco-footer-widget mb-4">
                          <h2 class="ftco-heading-2">Stories</h2>
                          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                          <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                          </ul>
                        </div>
                      </div>
                      <div class="col-md">
                        <div class="ftco-footer-widget mb-4 ml-md-5">
                          <h2 class="ftco-heading-2">Information</h2>
                          <ul class="list-unstyled">
                            <li><a href="#" class="py-2 d-block">Terms of Uses</a></li>
                            <li><a href="#" class="py-2 d-block">About Stories</a></li>
                            <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                            <li><a href="#" class="py-2 d-block">Accessibility Help</a></li>
                            <li><a href="#" class="py-2 d-block">Advertise with us</a></li>
                          </ul>
                        </div>
                      </div>
                      <div class="col-md">
                         <div class="ftco-footer-widget mb-4">
                          <h2 class="ftco-heading-2">Categories</h2>
                          <ul class="list-unstyled">
                            <li><a href="#" class="py-2 d-block">Food</a></li>
                            <li><a href="#" class="py-2 d-block">Restaurant</a></li>
                            <li><a href="#" class="py-2 d-block">Dessert</a></li>
                            <li><a href="#" class="py-2 d-block">Lifestyle</a></li>
                            <li><a href="#" class="py-2 d-block">Recipes</a></li>
                          </ul>
                        </div>
                      </div>
                      <div class="col-md">
                        <div class="ftco-footer-widget mb-4">
                            <h2 class="ftco-heading-2">Have a Questions?</h2>
                            <div class="block-23 mb-3">
                                  <ul>
                                    <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
                                    <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                                    <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
                                  </ul>
                                </div>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 text-center">
                            
                          <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                          Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        
         <!-- loader -->
        <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

        <!-- Scripts -->
        <?= $this->inlineScript()
            /*
            ->prependFile($this->basePath('js/js_restaurant/jquery.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/jquery-migrate-3.0.1.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/popper.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/bootstrap.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/jquery.easing.1.3.js'))
            ->prependFile($this->basePath('js/js_restaurant/jquery.waypoints.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/jquery.stellar.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/owl.carousel.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/jquery.magnific-popup.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/aos.js'))
            ->prependFile($this->basePath('js/js_restaurant/jquery.animateNumber.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/scrollax.min.js'))
            ->prependFile($this->basePath('js/js_restaurant/google-map.js'))
            ->prependFile($this->basePath('js/js_restaurant/main.js'))
            */
            ->prependFile($this->basePath('js/js_restaurant/main.js'))
            ->prependFile($this->basePath('js/js_restaurant/google-map.js'))
            ->prependFile("https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false")            
            ->prependFile($this->basePath('js/js_restaurant/scrollax.min.js'))
                        ->prependFile($this->basePath('js/js_restaurant/my_js.js'))                 
                        //->prependFile($this->basePath('js/js_restaurant/jquery-3.2.1.min.js'))                
                                   
                        ->prependFile($this->basePath('js/js_restaurant/jquery.animateNumber.min.js'))
                        ->prependFile($this->basePath('js/js_restaurant/aos.js'))
                        ->prependFile($this->basePath('js/js_restaurant/jquery.magnific-popup.min.js'))
                        ->prependFile($this->basePath('js/js_restaurant/owl.carousel.min.js'))
                        ->prependFile($this->basePath('js/js_restaurant/jquery.stellar.min.js'))
                        ->prependFile($this->basePath('js/js_restaurant/jquery.waypoints.min.js'))
                        ->prependFile($this->basePath('js/js_restaurant/jquery.easing.1.3.js'))
                        ->prependFile($this->basePath('js/js_restaurant/bootstrap.min.js'))
                        ->prependFile($this->basePath('js/js_restaurant/popper.min.js'))
                        ->prependFile($this->basePath('js/js_restaurant/jquery-migrate-3.0.1.min.js'))
                        ->prependFile($this->basePath('js/js_restaurant/jquery.min.js'))
                                        
        ?>
    </body>
</html>


