<?php 

$form->get('user_email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'name@yourcompany.com'
]);

$form->get('user_name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=> 'Seva'
]);

$form->get('message')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Your text'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
//$form->prepare();

echo"hhh";
//die();

?>
hello Seva
<h1>User info</h1><?php //die(); ?>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form);  ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('user_name')); ?>
            <?= $this->formElement($form->get('user_name') ); ?>
            <?= $this->formElementErrors($form->get('user_name')); ?>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('user_email')); ?>
            <?= $this->formElement($form->get('user_email') ); ?>
            <?= $this->formElementErrors($form->get('user_email')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('message')); ?>
            <?= $this->formElement($form->get('message') ); ?>
            <?= $this->formElementErrors($form->get('message')); ?>
        </div>
        <div class="form-group">
            <?= $this->formElement($form->get('submit')) ?>
        </div>
        
        <?= $this->formElement($form->get('csrf')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>